### ISSUE TITLE
Not found file proxies :(

### ISSUE THREAD

**Issue by SoyJuandaFox777** [Fsocguy/Steam-Checker-2023#1]

**Comment by suddendance** [comment]
This is due to the fact that in version 1.0 I did not implement the method of checking the path to the files combos.txt, proxies.txt and good.txt. And so for further use you need to create files combos.txt, proxy.txt, good.txt, and then in the code itself insert the full path to these files. But I strongly recommend you to switch to version 2.0, because in it I fixed this issue, so now you just need to create a folder, move the script there, and when you run it, it will create these files one by one.
